### ISSUE TITLE
Uncaught ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by lolaswift** [simondevyoutube/ProceduralTerrain_Part10#2]
I'm just wondering if you know how to solve this? thx.

**Comment by lolaswift** [comment]
for those having the same issue. You can use vsc plugin fiveserver. it supports customized header and it's built in even.

**Comment by grimdeathr** [comment]
this still occurs and fiveserver does not work

**Comment by grimdeathr** [comment]
I tried vsc five-server plugin and clicked GoLive


issue still occurs
